# Generated by Django 3.2.10 on 2023-11-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categorydb',
        ),
    ]
