# Generated by Django 3.2.10 on 2023-11-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_categorydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pro_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pro_description', models.CharField(blank=True, max_length=100, null=True)),
                ('pro_price', models.IntegerField(blank=True, null=True)),
                ('pro_stock', models.IntegerField(blank=True, null=True)),
                ('pro_product_image', models.ImageField(blank=True, null=True, upload_to='product')),
            ],
        ),
    ]
