# Generated by Django 3.2.10 on 2023-11-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='pro_product_image1',
            field=models.ImageField(blank=True, null=True, upload_to='product1'),
        ),
        migrations.AddField(
            model_name='productdb',
            name='pro_product_image2',
            field=models.ImageField(blank=True, null=True, upload_to='product2'),
        ),
    ]
