# Generated by Django 4.2.11 on 2024-04-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_alter_productdb_pro_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='category2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ca2_description', models.CharField(blank=True, max_length=100, null=True)),
                ('ca2_image', models.ImageField(blank=True, null=True, upload_to='category2')),
            ],
        ),
    ]
