# Generated by Django 4.2.11 on 2024-05-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_cart_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_data',
            name='p_image',
            field=models.ImageField(blank=True, null=True, upload_to='cart_detail'),
        ),
    ]
