# Generated by Django 4.2.11 on 2024-05-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_alter_cart_data_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_data',
            name='p_image',
            field=models.ImageField(blank=True, null=True, upload_to='cart'),
        ),
    ]
