# Generated by Django 4.2.11 on 2024-05-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_alter_cart_data_p_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart_data',
        ),
    ]
