# Generated by Django 4.2.11 on 2024-05-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_delete_cart_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=100, null=True)),
                ('p_price', models.CharField(blank=True, max_length=100, null=True)),
                ('p_size', models.CharField(blank=True, max_length=100, null=True)),
                ('p_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('price_total', models.CharField(blank=True, max_length=100, null=True)),
                ('p_image', models.ImageField(blank=True, null=True, upload_to='Cart_image')),
            ],
        ),
    ]
