# Generated by Django 4.2.11 on 2024-05-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_cart_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_data',
            name='p_image',
            field=models.ImageField(blank=True, null=True, upload_to='cart_detail'),
        ),
        migrations.AlterField(
            model_name='cart_data',
            name='p_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cart_data',
            name='p_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart_data',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
