# Generated by Django 4.2.11 on 2024-05-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_orderdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdb',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
