# Generated by Django 4.2.11 on 2024-05-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_alter_orderdb_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdb',
            name='Product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
