# Generated by Django 4.2.11 on 2024-05-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_alter_orderdb_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdb',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='orderdb',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
