# Generated by Django 4.2.11 on 2024-05-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_rename_price_orderdb_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdb',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderdb',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderdb',
            name='Price',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdb',
            name='Quantity',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
