# Generated by Django 4.2.11 on 2024-05-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0008_alter_orderdb_price_alter_orderdb_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginsavedb',
            name='user_name',
        ),
        migrations.AddField(
            model_name='loginsavedb',
            name='user_nam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
