# Generated by Django 4.2.11 on 2024-05-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0009_remove_loginsavedb_user_name_loginsavedb_user_nam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginsavedb',
            name='user_nam',
        ),
        migrations.AddField(
            model_name='loginsavedb',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
